version: '2'
services:
    storemono-app:
        image: storemono
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://storemono-postgresql:5432/storemono
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8087:8087
    storemono-postgresql:
        extends:
            file: postgresql.yml
            service: storemono-postgresql
